
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JList;

public class JFGUI extends javax.swing.JFrame implements Serializable{

    WhatsApp whats;

    public void setLblSeuNome(String nome) {
        lblSeuNome.setText(nome);
    }

    public WhatsApp getWhats() {
        return whats;
    }

    public void setWhats(WhatsApp whats) {
        this.whats = whats;
    }

    public JList<String> getListContatos() {
        return listContatos;
    }

    public JFGUI(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contatoScrollPane = new javax.swing.JScrollPane();
        listContatos = new javax.swing.JList<>();
        txtEnviarMensagem = new javax.swing.JTextField();
        btnNovaMensagem = new javax.swing.JButton();
        conversaScrollPanel = new javax.swing.JScrollPane();
        txtConversa = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblOnline = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        btnReceber = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblSeuNome = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WhatsApp");
        setBackground(new java.awt.Color(134, 214, 111));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        listContatos.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        listContatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listContatosMouseClicked(evt);
            }
        });
        contatoScrollPane.setViewportView(listContatos);

        txtEnviarMensagem.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        txtEnviarMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnviarMensagemActionPerformed(evt);
            }
        });

        btnNovaMensagem.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        btnNovaMensagem.setText("Novo Contato");
        btnNovaMensagem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnNovaMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaMensagemActionPerformed(evt);
            }
        });

        txtConversa.setEditable(false);
        txtConversa.setColumns(20);
        txtConversa.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        txtConversa.setRows(5);
        conversaScrollPanel.setViewportView(txtConversa);

        jPanel1.setBackground(new java.awt.Color(52, 175, 35));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblNome.setBackground(new java.awt.Color(102, 255, 102));
        lblNome.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        lblNome.setText("...");

        lblOnline.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        lblOnline.setText("Online");

        lblTelefone.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        lblTelefone.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOnline)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(lblOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnEnviar.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnReceber.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        btnReceber.setText("Receber");
        btnReceber.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceberActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(52, 175, 35));

        lblSeuNome.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        lblSeuNome.setText("Nome");

        jComboBox1.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível", "Ocupado", "Ausente", "Off-line" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSeuNome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBox1, 0, 159, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeuNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contatoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnviarMensagem)
                            .addComponent(conversaScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovaMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conversaScrollPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEnviarMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contatoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovaMensagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReceber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshText() {

        txtEnviarMensagem.setText(null);
        txtConversa.setText(null);

        for (Mensagem msg : whats.conv.get(listContatos.getSelectedIndex()).msg) {
            
            txtConversa.setText(txtConversa.getText() + msg.toString());
        }
    }
    
    public void setFields(){
        
        Vector<String> vect = new Vector();
        
        for (int i = 0; i < whats.conv.size(); i++) {
            
            vect.add(whats.conv.get(i).getContato());
        }
        
        this.listContatos.setListData(vect);
        
        lblSeuNome.setText(whats.getNomeUser());
    }

    private void txtEnviarMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnviarMensagemActionPerformed

        whats.sendTo(listContatos.getSelectedIndex(), txtEnviarMensagem.getText());
        refreshText();

    }//GEN-LAST:event_txtEnviarMensagemActionPerformed

    private void listContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listContatosMouseClicked

        txtConversa.setText(null);
        lblNome.setText(listContatos.getSelectedValue());
        lblTelefone.setText(whats.conv.get(listContatos.getSelectedIndex()).getTelefone());
        refreshText();

    }//GEN-LAST:event_listContatosMouseClicked

    private void btnNovaMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaMensagemActionPerformed

        JFAddContato addContato = new JFAddContato(this);
        addContato.setVisible(true);
    }//GEN-LAST:event_btnNovaMensagemActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        whats.sendTo(listContatos.getSelectedIndex(), txtEnviarMensagem.getText());
        refreshText();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceberActionPerformed

        whats.receiveFrom(listContatos.getSelectedIndex(), whats.conv.get(listContatos.getSelectedIndex()).getTelefone(), txtEnviarMensagem.getText());
        refreshText();
    }//GEN-LAST:event_btnReceberActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        
        JFPesquisar janelaPesquisa = new JFPesquisar(this);
        janelaPesquisa.setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        Serializacao serial = new Serializacao("backup.wpp");
        serial.gravarBackup(whats);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnNovaMensagem;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnReceber;
    private javax.swing.JScrollPane contatoScrollPane;
    private javax.swing.JScrollPane conversaScrollPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblOnline;
    private javax.swing.JLabel lblSeuNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JList<String> listContatos;
    private javax.swing.JTextArea txtConversa;
    private javax.swing.JTextField txtEnviarMensagem;
    // End of variables declaration//GEN-END:variables

}
